{% set name = "plog" %}
{% set version = "1.1.7" %}
{% set sha256 = "97dbdad93a34f02cd8a718851dcc90f6e586aa3215cda5501055635c4cbe54b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/SergiusTheBest/plog/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('cxx') }}

test:
  commands:
    - test -d ${PREFIX}/include/plog  # [unix]
    - test -f ${PREFIX}/include/plog/Logger.h  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\plog\Logger.h (exit 1)  # [win]

about:
  home: https://github.com/SergiusTheBest/plog
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: portable, simple and extensible C++ logging library

extra:
  recipe-maintainers:
    - gouarin
